# Seguridad básica
# La contraseña se pasa por comando en el docker-compose, pero aquí definimos límites
maxmemory 256mb
maxmemory-policy allkeys-lru

# Persistencia: Guardar cambios en disco cada 60 seg si hay al menos 1 cambio
save 60 1
appendonly yes
appendfsync everysec

# Conectividad
bind 0.0.0.0